version: "3"

services:
  jekyll:
    image: jekyll/jekyll
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    command: jekyll serve --watch --force_polling
    ports:
      - 4000:4000
